tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
brew "composer"
brew "fzf"
brew "git-flow"
brew "python"
brew "hugo"
brew "jq"
brew "nodebrew"
brew "php@7.1", restart_service: true, link: true
brew "jesseduffield/lazydocker/lazydocker"
